spring:
  application:
    name: tu-auth-service
  cloud:
    vault:
      token: dev-token
      scheme: http
      kv:
        enabled: true
  config:
    import: vault://
  datasource:
    url: jdbc:postgresql://localhost:5432/security
    username: ${spring.datasource.user}
    password: ${spring.datasource.password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      client:
        registration:
          google.client-id: ${google-oauth2.client_id}
          google.client-secret: ${google-oauth2.client_secret}
server:
  port: 8090
management:
  endpoints:
    web:
      exposure:
        include: health # Add env to view the value of environmental variables
  endpoint:
    configprops:
      show-values: never # Set this to 'always' to view config property values in dev
    env:
      show-values: never # Set this to 'always' to view config values derived from env and HC Vault in dev