spring:
  application:
    name: program-service
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: test_db_username
    password: test_db_password
logging:
  level:
    root: info
