server:
  port: 8082
converter:
  resource-id: "gateway"
  principal-attribute: "preferred_username"
keycloak:
  realm: "TeamUp"
  clientId: ${keycloak.client-id}
  clientSecret: ${keycloak.client-secret}
  username: ${keycloak.username}
  password: ${keycloak.password}
  introspection-uri: http://localhost:8080/realms/${keycloak.realm}/protocol/openid-connect/token/introspect

spring:
  application:
    name: program-service
  cloud:
    vault:
      token: dev-token
      scheme: http
      kv:
        enabled: true
  config:
    import: vault://
  security:
    oauth2:
      resourceserver:
        opaquetoken:
          client-id: ${keycloak.clientId}
          client-secret: ${keycloak.clientSecret}
          introspection-uri: ${keycloak.introspection-uri}
logging:
  level:
    root: debug

